### ISSUE TITLE
Microsoft.Data.SqlClient.SNI not deployed along with ClickOnce

### ISSUE THREAD

**Issue by Siam1205** [dotnet/SqlClient#441]
### Describe the bug
The nuget package Microsoft.EntityFrameworkCore.SqlServer v3.1.2 needs the reference to 
Microsoft.Data.SqlClient.SNI v1.1.1. The SNI package is automatically added to the project when referencing the SqlServer v3.1.2 which is expected. When building the solution, the directories x64 and x86 are created as expected and everything works fine when started from the \bin\debug and \bin\release folders.

### To reproduce the issue
When deploying the solution using ClickOnce, both directories (x86 and x64) are not included so that the application does not work anymore as it lacks the SNI.dll reference. I cannot see a way to solve the issue since I cannot include the reference under 

```
ProjectName > Publish > Application Files...
```

I saw [this (fixed) issue](https://github.com/dotnet/SqlClient/issues/157) but for ClickOnce, it does not seem to be fixed.

### Expected behavior
When deploying the application using ClickOnce, the x64 and x86 directories including the native SNI.dll libraries are copied to the respective version directory inside the "Application Files" directory and referenced properly.

**Comment by cheenamalhotra** [comment]
Hi @Siam1205 

Are you using `msbuild /target:publish` to publish the same or some other tool?
Could you try using msbuild if not already and let us know if that works?

If not, please provide us a repro version of your ClickOnce application for us to investigate targets.

**Comment by cfaagaard** [comment]
We are experiencing the same bug.
To reproduce:
1. Create new wfp app (.net 4.7.2)
2. Add nuget “Microsoft.EntityFrameworkCore” (version 3.1.2)
3. Add nuget “Microsoft.EntityFrameworkCore.SqlServer” (version 3.1.2)
4. Build project (debug or release)
Check bin/debug folder. It contains the two folders x64 and x86 with the SNI.dll in each folder.
![image](https://user-images.githubusercontent.com/25353502/75224610-13b5ea00-57a9-11ea-8734-cec63f0bfe20.png)
If you publish same project (using visual studio 2019 (16.4.5)) the published folder looks like this:
![image](https://user-images.githubusercontent.com/25353502/75224629-1adcf800-57a9-11ea-9af1-8ae081244e86.png)

**Comment by Siam1205** [comment]
Thank you very much for your Quick reply. I am currently on vacation ehich is the reason for my bad response time.

According to your question: I am using the ClickOnce publish mechanism right from VS (I guess VS2017). Since I am on vacation I cannot try what you suggested right now. However:

> We are experiencing the same bug.
> To reproduce:
> 
> 1. Create new wfp app (.net 4.7.2)
> 2. Add nuget “Microsoft.EntityFrameworkCore” (version 3.1.2)
> 3. Add nuget “Microsoft.EntityFrameworkCore.SqlServer” (version 3.1.2)
> 4. Build project (debug or release)
>    Check bin/debug folder. It contains the two folders x64 and x86 with the SNI.dll in each folder.
>    ![image](https://user-images.githubusercontent.com/25353502/75224610-13b5ea00-57a9-11ea-8734-cec63f0bfe20.png)
>    If you publish same project (using visual studio 2019 (16.4.5)) the published folder looks like this:
>    ![image](https://user-images.githubusercontent.com/25353502/75224629-1adcf800-57a9-11ea-9af1-8ae081244e86.png)

This exactly depicts the issue. Thank you very much.

**Comment by Siam1205** [comment]
I am currently using a workaround by adding both directories as content to the WPF App. This way, they are deployed along with the application. This works but is not ideal.

**Comment by cfaagaard** [comment]
> I am currently using a workaround by adding both directories as content to the WPF App. This way, they are deployed along with the application. This works but is not ideal.

So do we right now :-)

**Comment by cheenamalhotra** [comment]
Thanks for the repro @cfaagaard and @Siam1205 

I was able to reproduce the problem and saw that the SNI files were copied to Publish directory instead of deployment folder. The support for Publish Dir is for Dotnet SDK applications but there is no internal deployment folder so this was not covered.

I was able to resolve this by adding below target to csproj:

```proj
  <Target Name="_CopySNIFilesToPublishFolder" AfterTargets="_CopyFilesToPublishFolder" 
            Condition="'$(CopySNIFiles)' != 'false' And
                      '$(_CopySNIFilesToPublishFolder)' != 'false' And
                      '$(_DeploymentApplicationDir)' != '' And
                      HasTrailingSlash('$(_DeploymentApplicationDir)') And
                      Exists('$(_DeploymentApplicationDir)')"
            Inputs="@(SNIFiles)"
            Outputs="@(SNIFiles -> '$(_DeploymentApplicationDir)%(RecursiveDir)%(Filename)%(Extension)')">
    <Copy SourceFiles="@(SNIFiles)"
          DestinationFiles="@(SNIFiles -> '$(_DeploymentApplicationDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
```

Below is the output:

![image](https://user-images.githubusercontent.com/13396919/75263026-3d1f4780-57a2-11ea-9d7e-0a3f8078af4b.png)

Let me know if you can get it working too, and we will plan to address this change in next SNI version.

**Comment by cfaagaard** [comment]
I can confirm it copies the directories and the dlls and pdbs…… and it gives a warning: "Warning: Publishing file 'SNI.pdb' that may contain sensitive or proprietary information."

In a clickonce-publish-scenario it should be sni.dll.deploy and no pdb published.

**Comment by cheenamalhotra** [comment]
> In a clickonce-publish-scenario it should be sni.dll.deploy and no pdb published.

I agree. I think it should apply to all "Publish" targets as symbols are not needed during publish.
I've handled that internally and will be taken care of.

**Comment by Siam1205** [comment]
I will try the workaround you provided, @cheenamalhotra once I get back to work. However, according to @cfaagaard it actually works. I guess there is no need for me to additionally verify it.

If I understand you correctly, with SqlClient v2.0.0, your `<Target>` workaround won't be necessary anymore?

**Comment by cheenamalhotra** [comment]
Yes, the above target (with handled pdb case) will be part of M.D.S.SNI.targets in next release.

**Comment by Siam1205** [comment]
> ```
>   <Target Name="_CopySNIFilesToPublishFolder" AfterTargets="_CopyFilesToPublishFolder" 
>             Condition="'$(CopySNIFiles)' != 'false' And
>                       '$(_CopySNIFilesToPublishFolder)' != 'false' And
>                       '$(_DeploymentApplicationDir)' != '' And
>                       HasTrailingSlash('$(_DeploymentApplicationDir)') And
>                       Exists('$(_DeploymentApplicationDir)')"
>             Inputs="@(SNIFiles)"
>             Outputs="@(SNIFiles -> '$(_DeploymentApplicationDir)%(RecursiveDir)%(Filename)%(Extension)')">
>     <Copy SourceFiles="@(SNIFiles)"
>           DestinationFiles="@(SNIFiles -> '$(_DeploymentApplicationDir)%(RecursiveDir)%(Filename)%(Extension)')" />
>   </Target>
> ```

I can also confirm that this workaround solves the issue. I will use that until it becomes obsolete. Thank you very much for your efforts.

**Comment by Siam1205** [comment]
Hello,

I must add the fact that the provided workaround indeed copies the files as expected. However: While installing the latest version of the application, it does not seem to copy the files to where the whole application is deployed locally hence the workaround does not work for ClickOnce applications that are installed locally upon starting the `setup.exe` or the `.application` file in the output directory.

**Comment by jeremy-waguet** [comment]
@Siam1205 
Exactly same bahaviour for me deployed but not copied locally !

**Comment by jeremy-waguet** [comment]
For those who encountered the same issue I have, I stored SNI.dll to publishing directory and I check if it exists at each application start. If it doesn’t I download them to the application directory. That sounds to be the UGLIEST HACK I ever done ! Hope to drop that code very soon.
Here is my sample code for reference this has to be before any connection to database so in main static method it’s okay @Siam1205  :

```c#
/// <summary>
/// The main entry point for the application.
/// </summary>
[STAThread]
private static void Main()
{
    // HACK : Download SNI.dll manualy waiting that should be deployed as part of the 'Microsoft.Data.SqlClient.SNI' package by clickonce but is NOT deployed due to bug here : https://github.com/dotnet/SqlClient/issues/441
    string applicationDirectoryPath = Path.GetDirectoryName(Application.ExecutablePath);
    string x86SNIDirectoryPath = Path.Combine(applicationDirectoryPath, "x86");
    if (!Directory.Exists(x86SNIDirectoryPath))
    {
        Directory.CreateDirectory(x86SNIDirectoryPath);
        using (WebClient client = new WebClient())
        {
            client.DownloadFile("https://clickoncedeploydomain.tld/ClickOnceDeployDirectory/x86/SNI.dll.deploy", Path.Combine(x86SNIDirectoryPath, "SNI.dll"));
        }
    }
    string x64SNIDirectoryPath = Path.Combine(applicationDirectoryPath, "x64");
    if (!Directory.Exists(x64SNIDirectoryPath))
    {
        Directory.CreateDirectory(x64SNIDirectoryPath);
        using (WebClient client = new WebClient())
        {
            client.DownloadFile("https://clickoncedeploydomain.tld/ClickOnceDeployDirectory/x64/SNI.dll.deploy", Path.Combine(x64SNIDirectoryPath, "SNI.dll"));
        }
    }
    ...
}
```

**Comment by linusaurus** [comment]
I have a Winforms application .NET 4.8, and a data layer project that uses netstandard 2.0. and Microsoft.data.Sqlclient 1.1.2. In the development environment it works perfectly accessing data from Sql Server. When I deploy it using clickonce or MSLX the app will error with Microsoft.data.Sql.TdsParser failed to initialize. I have added Microsoft.Data.SqlClient.SNI to the project. Cant find any way to deploy the Application.

**Comment by jeremy-waguet** [comment]
Hi @linusaurus 
Either use my UGLY hack published above or copy x86/SNI.dll and x64/SNI.dll as "Content" resource (that will be deployed as part of the ClickOnce or MSIX deployment) as suggested by @Siam1205 . For now these are the only known workarounds waiting for a further release that fix this issue !

**Comment by linusaurus** [comment]
I found in lacking any other way forward with distributing the application internally, that simply copying the bin/Release files to a network location and using a shortcut to the exe file in that folder to the users machine worked perfectly. Certainly not as elegant as the click-once, but strangely almost as easy. Even when I did copy the x86 and x64 folders with the SNI.dll in them it still didn't work.

**Comment by jeremy-waguet** [comment]
@linusaurus 

Here is exactly what I did for my own project since I am using a web server for my ClickOnce updates but I think the same could work to a network location as well by replacing WebClient API with File.Copy API instead:
* Upload "x86/SNI.dll" & "x64/SNI.dll" to my clickonce deployment directory (eg: "https://clickoncedeploydomain.tld/ClickOnceDeployDirectory/" with the '.deploy' suffix in my case. You'll need to keep the DLLs up to date with your "Microsoft.Data.SqlClient.SNI" nuget package
* use this sample code as soon as possible (eg in the main function before using Microsoft.Data.SqlClient API)
```c#
/// <summary>
/// The main entry point for the application.
/// </summary>
[STAThread]
private static void Main()
{
    // HACK : Download SNI.dll manualy waiting that should be deployed as part of the 'Microsoft.Data.SqlClient.SNI' package by clickonce but is NOT deployed due to bug here : https://github.com/dotnet/SqlClient/issues/441
    string applicationDirectoryPath = Path.GetDirectoryName(Application.ExecutablePath);
    string x86SNIDirectoryPath = Path.Combine(applicationDirectoryPath, "x86");
    if (!Directory.Exists(x86SNIDirectoryPath))
    {
        Directory.CreateDirectory(x86SNIDirectoryPath);
        using (WebClient client = new WebClient())
        {
            client.DownloadFile("https://clickoncedeploydomain.tld/ClickOnceDeployDirectory/x86/SNI.dll.deploy", Path.Combine(x86SNIDirectoryPath, "SNI.dll"));
        }
    }
    string x64SNIDirectoryPath = Path.Combine(applicationDirectoryPath, "x64");
    if (!Directory.Exists(x64SNIDirectoryPath))
    {
        Directory.CreateDirectory(x64SNIDirectoryPath);
        using (WebClient client = new WebClient())
        {
            client.DownloadFile("https://clickoncedeploydomain.tld/ClickOnceDeployDirectory/x64/SNI.dll.deploy", Path.Combine(x64SNIDirectoryPath, "SNI.dll"));
        }
    }
    ...
}
```

**Comment by rpfeuti** [comment]
Hi. I had the same behavior in my project, and I don't have Entity Framework.
The project is a VSTO 4.72 .net framework class library on a solution with another projects pointing to .net standard 2 and the main is a WPF application .net core. The problem was solved copping x64 and x86 folder into VSTO Add In and deploying together. Thank you guys!

**Comment by cheenamalhotra** [comment]
Hi everyone,

The latest release of [Microsoft.Data.SqlClient v2.0.0-preview4](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.0.0-preview4.20142.4) introduces modifications for SNI.dll for .NET Framework. It has now been renamed to `Microsoft.Data.SqlClient.SNI.x64.dll` and `Microsoft.Data.SqlClient.SNI.x86.dll` and is now downloaded transitively to same `bin` folder as `Microsoft.Data.SqlClient.dll`. It also now allows client applications to place these DLLs to the location of your preference as starting this version, the driver does not load these DLLs with relative path reference.

[Release Notes](https://github.com/dotnet/SqlClient/blob/master/release-notes/2.0/2.0.0-preview4.md)
_Please make a note of this change when working on .NET Framework applications referencing DLLs by their name._

**Comment by Siam1205** [comment]
Hi,

thank you for your update. I updated the SqlClient to the newest preview package that you suggested via nuget. I can confirm the name changes you mentioned as well as the fact that the `.dll `files are copied to the same bin folder as `Microsoft.Data.SqlClient.dll`.

Nevertheless, I cannot check whether the ClickOnce-deployed solution works because I've encountered new problems after upgrading the packages. When I start the application, at some point I cannot access the database because of a new exception that I've never seen before:

`Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Threading.Tasks.Extensions`.

I could not find a solution for this issue so I reverted all changes back to the workaround I mentioned on Feb 25 while using the 'old' versions `1.1.1`. Because of this, I cannot hand you more information on how the error occurred or whether it is really related directly to the SqlClient package at this point.

I just post this information here because I am curious of whether anyone else encounters similar issues.

**Comment by jeremy-waguet** [comment]
@Siam1205 Did you upgrade 'Microsoft.Data.SqlClient.dll' as well? I suppose you did. But I had a similar issue yesterday (late). Now I upgraded both packages (‘Microsoft.Data.SqlClient' and 'Microsoft.Data.SqlClient.SNI' and it seems to work well. I am doing some other tests ... to make sure it is really deployable with ClickOnce (and MSIX by the way)

**Comment by jeremy-waguet** [comment]
Unfortunately, the two DLLs are not part of the .manifest file and they do not have the default .deploy suffix. Once installed I encounter the ‘System.DllNotFoundException: Impossible de charger la DLL 'Microsoft.Data.SqlClient.SNI.x64.dll': Le module spécifié est introuvable. (Exception de HRESULT : 0x8007007E)’ since it is not part of the ClickOnce manifest. I have to revert to the older version as well :(

**Comment by jeremy-waguet** [comment]
I may be wrong but I think ClickOnce has been designed to include only managed DLLs and static resources. Maybe this issue can’t be solved another way than publishing these DLLs as static assets which now has to be deployed directly at the root directory and no more ‘x86’ & ‘x64’. I don't understand how ClickOnce works enough for a workaround proposal :(

**Comment by jeremy-waguet** [comment]
@Siam1205 @cheenamalhotra 
Since I can't find the 'Microsoft.Data.SqlClient.SNI.targets' file in the Microsoft.Data.SqlClient repository here is a WORKING revision that WORKS with ClickOnce without patching the your csproj at all:

I was inspired by this topic : https://stackoverflow.com/questions/45420114/clickonce-include-imported-targets-when-publishing-ffmpeg

To replace the Microsoft.Data.SqlClient.SNI.targets file with this patched one : 
```xml
<!--
 *
 * Microsoft.Data.SqlClient.SNI.targets -
 *
 * WARNING: This MSBuild file requires MSBuild 4.0 features.
 *
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!--
  ******************************************************************************
  **                          Load Per-User Settings                          **
  ******************************************************************************
  -->

  <!--
      NOTE: If the per-user settings file exists, import it now.  The contained
            settings, if any, will override the default ones provided below.
  -->
  <Import Condition="'$(MSBuildThisFileDirectory)' != '' And
                     HasTrailingSlash('$(MSBuildThisFileDirectory)') And
                     Exists('$(MSBuildThisFileDirectory)Microsoft.Data.SqlClient.SNI.targets.user')"
          Project="$(MSBuildThisFileDirectory)Microsoft.Data.SqlClient.SNI.targets.user" />

  <!--
  ******************************************************************************
  **                           Library Build Items                            **
  ******************************************************************************
  -->

  <ItemGroup>
    <SNIDllFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                    HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*.dll" />
    <SNIFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                   HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*"
                        Exclude="$(MSBuildThisFileDirectory)**\*.targets" />
  </ItemGroup>

  <ItemGroup>
    <ClickOnce Include="@(SNIDllFiles)">
      <InProject>false</InProject>
      <Visible>false</Visible>
    </ClickOnce>
  </ItemGroup>
  
  <!--
  ******************************************************************************
  **                          Library Content Items                           **
  ******************************************************************************
  -->

  <ItemGroup Condition="'$(ContentSNIFiles)' != '' And
                        '$(ContentSNIFiles)' != 'false' And
                        '@(SNIFiles)' != ''">
    <Content Include="@(SNIFiles)">
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!--
  ******************************************************************************
  **                          Library Build Targets                           **
  ******************************************************************************
  -->

  <Target Name="CopySNIFiles"
          Condition="'$(CopySNIFiles)' != 'false' And
                     '$(OutDir)' != '' And
                     HasTrailingSlash('$(OutDir)') And
                     Exists('$(OutDir)')"
          Inputs="@(SNIFiles)"
          Outputs="@(SNIFiles -> '$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')">
    <!--
        NOTE: Copy "Microsoft.Data.SqlClient.SNI.dll" and all related files, for every
              architecture that we support, to the build output directory.        
    -->
    <Copy SourceFiles="@(SNIFiles)"
          DestinationFiles="@(SNIFiles -> '$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <Target Name="CopySNIRoleFiles"
          Condition="'@(WorkerRoleReferences)' != ''"
          Inputs="@(SNIFiles)"
          Outputs="@(SNIFiles -> '$(_IntermediateWorkerOutputPath)%(RecursiveDir)%(Filename)%(Extension)')">
    <!--
        NOTE: Copy "Microsoft.Data.SqlClient.SNI.dll" and all related files, for every
              architecture that we support, to the build output directory.        
    -->
    <PropertyGroup>
      <_IntermediateWorkerOutputPath>%(WorkerRoleReferences.OutputDir)</_IntermediateWorkerOutputPath>
    </PropertyGroup>

    <Copy SourceFiles="@(SNIFiles)"
          DestinationFiles="@(SNIFiles -> '$(_IntermediateWorkerOutputPath)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <Target Name="AppendSNIDllsInManifest" Condition="'@(ClickOnce)' != ''" AfterTargets="BeforeBuild">
    <CreateItem Include="@(ClickOnce)" AdditionalMetadata="TargetPath=%(FileName)%(Extension);IsDataFile=false">
      <Output TaskParameter="Include" ItemName="_DeploymentManifestFiles" />
    </CreateItem>
  </Target>
  
  <Target Name="PublishSNIFiles" AfterTargets="Publish"
          Condition="'$(CopySNIFiles)' != 'false' And
                     '$(PublishSNIFiles)' != 'false' And
                     '$(PublishDir)' != '' And
                     '$(_DeploymentApplicationDir)' == '' And
                     HasTrailingSlash('$(PublishDir)') And
                     Exists('$(PublishDir)') And
                     '@(ClickOnce)' != ''"
          Inputs="@(SNIDllFiles)"
          Outputs="@(SNIDllFiles -> '$(PublishDir)%(RecursiveDir)%(Filename)%(Extension)')">
    <!--
        NOTE: Copy "Microsoft.Data.SqlClient.SNI.dll" only to the publish directory.

    -->
    <Copy SourceFiles="@(SNIDllFiles)"
          DestinationFiles="@(SNIDllFiles -> '$(PublishDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <!--<Target Name="_CopySNIFilesToPublishFolder" AfterTargets="_CopyFilesToPublishFolder" 
            Condition="'$(CopySNIFiles)' != 'false' And
                      '$(_CopySNIFilesToPublishFolder)' != 'false' And
                      '$(_DeploymentApplicationDir)' != '' And
                      HasTrailingSlash('$(_DeploymentApplicationDir)') And
                      Exists('$(_DeploymentApplicationDir)')"
            Inputs="@(SNIDllFiles)"
            Outputs="@(SNIDllFiles -> '$(_DeploymentApplicationDir)%(RecursiveDir)%(Filename)%(Extension)')">
    --><!--
        NOTE: Copy "Microsoft.Data.SqlClient.SNI.dll" only to the publish output directory.
    --><!--
    <Copy SourceFiles="@(SNIDllFiles)"
          DestinationFiles="@(SNIDllFiles -> '$(_DeploymentApplicationDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>-->

  <!--
  ******************************************************************************
  -->

  <Target Name="CleanSNIFiles"
          Condition="'$(CleanSNIFiles)' != 'false' And
                     '$(OutDir)' != '' And
                     HasTrailingSlash('$(OutDir)') And
                     Exists('$(OutDir)')">
    <!--
        NOTE: Delete "Microsoft.Data.SqlClient.SNI.dll" and all related files, for every
              architecture that we support, from the build output directory.
    -->
    <Delete Files="@(SNIFiles -> '$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <!--
  ******************************************************************************
  -->

  <Target Name="CollectSNIFiles"
          Condition="'$(CollectSNIFiles)' != 'false'">
    <ItemGroup>
      <FilesForPackagingFromProject Include="@(SNIFiles)">
        <DestinationRelativePath>bin\%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
      </FilesForPackagingFromProject>
    </ItemGroup>
  </Target>

  <!--
  ******************************************************************************
  **                         Library Build Properties                         **
  ******************************************************************************
  -->

  <PropertyGroup>
    <PostBuildEventDependsOn>
      $(PostBuildEventDependsOn);
      CopySNIFiles;
    </PostBuildEventDependsOn>
    <PublishItemsOutputGroupDependsOn>
      $(PublishItemsOutputGroupDependsOn);
      PublishSNIFiles;
    </PublishItemsOutputGroupDependsOn>
    <BuildDependsOn>
      $(BuildDependsOn);
      CopySNIFiles;
    </BuildDependsOn>
    <PrepareForRunDependsOn>
      $(PrepareForRunDependsOn);
      CopySNIFiles;
    </PrepareForRunDependsOn>
    <CleanDependsOn>
      $(CleanDependsOn);
      CleanSNIFiles;
    </CleanDependsOn>
  </PropertyGroup>

  <!--
  ******************************************************************************
  **            Library Publish Properties for Visual Studio 201x             **
  ******************************************************************************
  -->

  <PropertyGroup>
    <PipelineCollectFilesPhaseDependsOn>
      CollectSNIFiles;
      $(PipelineCollectFilesPhaseDependsOn);
    </PipelineCollectFilesPhaseDependsOn>
    <CollectRoleFilesDependsOn>
      $(CollectRoleFilesDependsOn);
      CollectSNIFiles;
    </CollectRoleFilesDependsOn>
    <CopyRoleFilesDependsOn>
      $(CopyRoleFilesDependsOn)
      CopySNIRoleFiles;
    </CopyRoleFilesDependsOn>
  </PropertyGroup>
</Project>
```

**Comment by cheenamalhotra** [comment]
Hi @jeremy-waguet 

Thanks for sharing updated file. I was about to look into Manifest inclusion after you shared the missing element above. Also ClickOnce Documentations led to the same theory, as I read here: https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-security-and-deployment?view=vs-2019#publish-clickonce-applications

I tested and it seems good to me! I also saw you commented out the 'CopySNIFilesToPublishFolder" target, which was discussed above in this thread and therefore added. I will look more into it whether the changes offer a complete replacement to this target or it would be needed for any other scenario. Could you confirm too this is not needed?

@Siam1205 could you also try and let us know if the targets file shared by @jeremy-waguet above works for you as desired to fix this issue?

**Comment by jeremy-waguet** [comment]
@cheenamalhotra I commented out the CopySNIFilesToPublishFolder target because it is working properly on my project without this (files get copied to the "bin\$Configuration\app.publish" directory and also copied to the final "publish\Application Files\*"). I may be still be required in other configurations or project types ...

Please note that It also works by merging to two item (minor optimization) groups like that from :
```xml
<ItemGroup>
    <SNIDllFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                    HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*.dll" />
    <SNIFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                   HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*"
                        Exclude="$(MSBuildThisFileDirectory)**\*.targets" />
  </ItemGroup>

  <ItemGroup>
    <ClickOnce Include="@(SNIDllFiles)">
      <InProject>false</InProject>
      <Visible>false</Visible>
    </ClickOnce>
  </ItemGroup>
```

to
```xml
  <ItemGroup>
    <SNIDllFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                    HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*.dll" />
    <SNIFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                   HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*"
                        Exclude="$(MSBuildThisFileDirectory)**\*.targets" />

    <ClickOnce Include="@(SNIDllFiles)">
      <InProject>false</InProject>
      <Visible>false</Visible>
    </ClickOnce>
  </ItemGroup>
```

**Comment by jeremy-waguet** [comment]
@cheenamalhotra Even better; condition the ClickOnce element with non empty @(SNIDllFiles) variable like this :
```xml
<ItemGroup>
    <SNIDllFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                    HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*.dll" />
    <SNIFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                   HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*"
                        Exclude="$(MSBuildThisFileDirectory)**\*.targets" />

    <ClickOnce Condition="@(SNIDllFiles) != ''" Include="@(SNIDllFiles)">
      <InProject>false</InProject>
      <Visible>false</Visible>
    </ClickOnce>
  </ItemGroup>
```

**Comment by jeremy-waguet** [comment]
I tried :
* on a sample Windows Forms project : Works as expected
* on a sample WPF project : Works as expected
* on a sample MSIX project attached to the Windows Forms project : DOESN'T work yet
* on a sample MSIX project attached to the WPF project: DOESN'T work yet
For MSIX projects SNI DLLs are NOT packaged along with Microsoft.Data.SqlClient.dll

**Comment by jeremy-waguet** [comment]
I also tried :
* on a sample Console project : Works as expected
* on a sample WebForm project with file system deploy : SNI dlls are present but PDBs are also even with 'Exclude generated debug symbols' checkbox enabled
* on a sample WebForm project with WebDeploy package : SNI dlls are present but PDBs are also even with 'Exclude generated debug symbols' checkbox enabled
* on a sample MFC WebForm project with file system deploy : SNI dlls are present but PDBs are also even with 'Exclude generated debug symbols' checkbox enabled
* on a sample MFC WebForm project with WebDeploy package : SNI dlls are present but PDBs are also even with 'Exclude generated debug symbols' checkbox enabled

As a conclusion, classical desktop / web deployment scenarios appear to work except for MSIX based deployments. I suppose it doesn't work for Windows Universal Apps as it relies on MSIX. I did not try Azure or Docker deployments for web projects.

**Comment by cheenamalhotra** [comment]
Hi @jeremy-waguet 

Thanks for your insights, we released v2.0.0 to include ClickOnce targets, please give that a try and let us know. We will continue to investigate other deployment areas to provide support.

**Comment by cheenamalhotra** [comment]
Closing this issue in regard to Clickonce application support.

**Comment by jeremy-waguet** [comment]
Hi @cheenamalhotra 

I can confirm it DOES work but the original DLLs still get copied to publish directory because of the "_CopySNIFilesToPublishFolder" target (but these files are not used by ClickOnce as they are not part of the deployment manifest file):

![image](https://user-images.githubusercontent.com/62789184/84983621-6c830700-b139-11ea-8aef-ec2f3ae77b8b.png)

I really don't see any area where this should be needed (at least with ClickOnce). By removing this target, the DLLs are no more present in the publish directory (but still included in the ClickOnce manifest, hence downloaded and used):

![image](https://user-images.githubusercontent.com/62789184/84983953-29756380-b13a-11ea-807c-6b416cd39169.png)

Finally, I merged both ItemGroups as It is working perfectly with one ItemGroup (simple is better, isn’t?)

I also kept the "PublishSNIFiles" target as I could be used in non-ClickOnce scenario (but I don't know if it ever is). For a ClickOnce deployment this target is not needed.

As a proposal, here is a working version of the "Microsoft.Data.SqlClient.SNI.targets" file that works with every ClickOnce deployment mentioned above:

```xml
<!--
 *
 * Microsoft.Data.SqlClient.SNI.targets -
 *
 * WARNING: This MSBuild file requires MSBuild 4.0 features.
 *
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!--
  ******************************************************************************
  **                          Load Per-User Settings                          **
  ******************************************************************************
  -->

  <!--
      NOTE: If the per-user settings file exists, import it now.  The contained
            settings, if any, will override the default ones provided below.
  -->
  <Import Condition="'$(MSBuildThisFileDirectory)' != '' And
                     HasTrailingSlash('$(MSBuildThisFileDirectory)') And
                     Exists('$(MSBuildThisFileDirectory)Microsoft.Data.SqlClient.SNI.targets.user')"
          Project="$(MSBuildThisFileDirectory)Microsoft.Data.SqlClient.SNI.targets.user" />

  <!--
  ******************************************************************************
  **                           Library Build Items                            **
  ******************************************************************************
  -->

  <ItemGroup>
    <SNIDllFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                    HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*.dll" />
    <SNIFiles Condition="'$(MSBuildThisFileDirectory)' != '' And
                                   HasTrailingSlash('$(MSBuildThisFileDirectory)')"
                        Include="$(MSBuildThisFileDirectory)**\Microsoft.Data.SqlClient.SNI.*"
                        Exclude="$(MSBuildThisFileDirectory)**\*.targets" />

    <ClickOnce Condition="@(SNIDllFiles) != ''" Include="@(SNIDllFiles)">
      <InProject>false</InProject>
      <Visible>false</Visible>
    </ClickOnce>
  </ItemGroup>
  
  <!--
  ******************************************************************************
  **                          Library Content Items                           **
  ******************************************************************************
  -->

  <ItemGroup Condition="'$(ContentSNIFiles)' != '' And
                        '$(ContentSNIFiles)' != 'false' And
                        '@(SNIFiles)' != ''">
    <Content Include="@(SNIFiles)">
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!--
  ******************************************************************************
  **                          Library Build Targets                           **
  ******************************************************************************
  -->

  <Target Name="CopySNIFiles"
          Condition="'$(CopySNIFiles)' != 'false' And
                     '$(OutDir)' != '' And
                     HasTrailingSlash('$(OutDir)') And
                     Exists('$(OutDir)')"
          Inputs="@(SNIFiles)"
          Outputs="@(SNIFiles -> '$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')">
    <!--
        NOTE: Copy "Microsoft.Data.SqlClient.SNI.dll" and all related files, for every
              architecture that we support, to the build output directory.        
    -->
    <Copy SourceFiles="@(SNIFiles)"
          DestinationFiles="@(SNIFiles -> '$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <Target Name="CopySNIRoleFiles"
          Condition="'@(WorkerRoleReferences)' != ''"
          Inputs="@(SNIFiles)"
          Outputs="@(SNIFiles -> '$(_IntermediateWorkerOutputPath)%(RecursiveDir)%(Filename)%(Extension)')">
    <!--
        NOTE: Copy "Microsoft.Data.SqlClient.SNI.dll" and all related files, for every
              architecture that we support, to the build output directory.        
    -->
    <PropertyGroup>
      <_IntermediateWorkerOutputPath>%(WorkerRoleReferences.OutputDir)</_IntermediateWorkerOutputPath>
    </PropertyGroup>

    <Copy SourceFiles="@(SNIFiles)"
          DestinationFiles="@(SNIFiles -> '$(_IntermediateWorkerOutputPath)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <Target Name="AppendSNIDllsInManifest" Condition="'@(ClickOnce)' != ''" AfterTargets="BeforeBuild">
    <CreateItem Include="@(ClickOnce)" AdditionalMetadata="TargetPath=%(FileName)%(Extension);IsDataFile=false">
      <Output TaskParameter="Include" ItemName="_DeploymentManifestFiles" />
    </CreateItem>
  </Target>
  
  <Target Name="PublishSNIFiles" AfterTargets="Publish"
          Condition="'$(CopySNIFiles)' != 'false' And
                     '$(PublishSNIFiles)' != 'false' And
                     '$(PublishDir)' != '' And
                     '$(_DeploymentApplicationDir)' == '' And
                     HasTrailingSlash('$(PublishDir)') And
                     Exists('$(PublishDir)') And
                     '@(ClickOnce)' != ''"
          Inputs="@(SNIDllFiles)"
          Outputs="@(SNIDllFiles -> '$(PublishDir)%(RecursiveDir)%(Filename)%(Extension)')">
    <!--
        NOTE: Copy "Microsoft.Data.SqlClient.SNI.dll" only to the publish directory.

    -->
    <Copy SourceFiles="@(SNIDllFiles)"
          DestinationFiles="@(SNIDllFiles -> '$(PublishDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <!--
  ******************************************************************************
  -->

  <Target Name="CleanSNIFiles"
          Condition="'$(CleanSNIFiles)' != 'false' And
                     '$(OutDir)' != '' And
                     HasTrailingSlash('$(OutDir)') And
                     Exists('$(OutDir)')">
    <!--
        NOTE: Delete "Microsoft.Data.SqlClient.SNI.dll" and all related files, for every
              architecture that we support, from the build output directory.
    -->
    <Delete Files="@(SNIFiles -> '$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>

  <!--
  ******************************************************************************
  -->

  <Target Name="CollectSNIFiles"
          Condition="'$(CollectSNIFiles)' != 'false'">
    <ItemGroup>
      <FilesForPackagingFromProject Include="@(SNIFiles)">
        <DestinationRelativePath>bin\%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
      </FilesForPackagingFromProject>
    </ItemGroup>
  </Target>

  <!--
  ******************************************************************************
  **                         Library Build Properties                         **
  ******************************************************************************
  -->

  <PropertyGroup>
    <PostBuildEventDependsOn>
      $(PostBuildEventDependsOn);
      CopySNIFiles;
    </PostBuildEventDependsOn>
    <PublishItemsOutputGroupDependsOn>
      $(PublishItemsOutputGroupDependsOn);
      PublishSNIFiles;
    </PublishItemsOutputGroupDependsOn>
    <BuildDependsOn>
      $(BuildDependsOn);
      CopySNIFiles;
    </BuildDependsOn>
    <PrepareForRunDependsOn>
      $(PrepareForRunDependsOn);
      CopySNIFiles;
    </PrepareForRunDependsOn>
    <CleanDependsOn>
      $(CleanDependsOn);
      CleanSNIFiles;
    </CleanDependsOn>
  </PropertyGroup>

  <!--
  ******************************************************************************
  **            Library Publish Properties for Visual Studio 201x             **
  ******************************************************************************
  -->

  <PropertyGroup>
    <PipelineCollectFilesPhaseDependsOn>
      CollectSNIFiles;
      $(PipelineCollectFilesPhaseDependsOn);
    </PipelineCollectFilesPhaseDependsOn>
    <CollectRoleFilesDependsOn>
      $(CollectRoleFilesDependsOn);
      CollectSNIFiles;
    </CollectRoleFilesDependsOn>
    <CopyRoleFilesDependsOn>
      $(CopyRoleFilesDependsOn)
      CopySNIRoleFiles;
    </CopyRoleFilesDependsOn>
  </PropertyGroup>
</Project>
```

In addition to that, WebDeploy (folder & packages) also works and PDB are now EXCLUDED from the packages maybe due to a VS update? or an issue with my past tests

Thank you for fixing this issue and making .NET ecosystem better !

**Comment by cheenamalhotra** [comment]
Hi @jeremy-waguet 

I chose to keep the target in case it's required by any other deployment vehicle. But you may ignore these files.
Thanks for your feedback and testing efforts!

Would you be able to provide a repro app on issue #612 if that still exists as we haven't begun efforts on that one and wanted to check with you if it's reproducible and you could provide repro steps for the same? We're not experts in all deployment domains so a repro app is beneficial to investigate and provide a fix.

**Comment by aibrahim2020** [comment]
> Thanks for the repro @cfaagaard and @Siam1205
> 
> I was able to reproduce the problem and saw that the SNI files were copied to Publish directory instead of deployment folder. The support for Publish Dir is for Dotnet SDK applications but there is no internal deployment folder so this was not covered.
> 
> I was able to resolve this by adding below target to csproj:
> 
> ```
>   <Target Name="_CopySNIFilesToPublishFolder" AfterTargets="_CopyFilesToPublishFolder" 
>             Condition="'$(CopySNIFiles)' != 'false' And
>                       '$(_CopySNIFilesToPublishFolder)' != 'false' And
>                       '$(_DeploymentApplicationDir)' != '' And
>                       HasTrailingSlash('$(_DeploymentApplicationDir)') And
>                       Exists('$(_DeploymentApplicationDir)')"
>             Inputs="@(SNIFiles)"
>             Outputs="@(SNIFiles -> '$(_DeploymentApplicationDir)%(RecursiveDir)%(Filename)%(Extension)')">
>     <Copy SourceFiles="@(SNIFiles)"
>           DestinationFiles="@(SNIFiles -> '$(_DeploymentApplicationDir)%(RecursiveDir)%(Filename)%(Extension)')" />
>   </Target>
> ```
> 
> Below is the output:
> 
> ![image](https://user-images.githubusercontent.com/13396919/75263026-3d1f4780-57a2-11ea-9d7e-0a3f8078af4b.png)
> 
> Let me know if you can get it working too, and we will plan to address this change in next SNI version.

could you please update that target to copy the files to %WindDir%\system32 as I need to deploy office Add-in

**Comment by cheenamalhotra** [comment]
We cannot update the target to copy to `%WindDir%\system32` location due to privilege concerns.
You may override the target by modifying and including it in your csproj as per your needs.

**Comment by Siam1205** [comment]
Hello @cheenamalhotra and @jeremy-waguet,

sorry that I did not respond to you for so long and thank you for continuing to find a solution for the issue.

The respective project still uses the workaround I mentioned on Feb 25. 
I read briefly through your discussion but I wonder what the best solution now looks like. So what's the best way to get the ClickOnce deployment working properly without manipulating too much the project itself too much?

**Comment by Siam1205** [comment]
> Nevertheless, I cannot check whether the ClickOnce-deployed solution works because I've encountered new problems after upgrading the packages. When I start the application, at some point I cannot access the database because of a new exception that I've never seen before:
> 
> `Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Threading.Tasks.Extensions`.

FYI: I fixed this and following issues by adding

```
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```

to the corresponding `.csproj` file.

**Comment by cheenamalhotra** [comment]
Hi @Siam1205 

Starting with v2.0.0 of Microsoft.Data.SqlClient, you should not have issues with Clickonce application deployments.
Please upgrade and let us know if you face any issues! A new issue with repro in that case would be ideal.

**Comment by tatoadsl** [comment]
Hello,

This seems to be not solved or at least I can't make it work properly even trying the many workaround proposed here.
My project is .NET 5 using EF Core 5.0. The dependency uses is Microsoft.Data.SqlClient 2.0.1 and the files are not deployed with ClickOnce.

The problem is the same, can't find the Microsoft.Data.SqlClient.SNI.dll file as it is not copy to the deploy folder using ClickOnce publish.

Seems it is solved when targeting a .NET Framework project but not when it is with a .NET Core project.

Any expectation of a solution for this. Now that ClickOnce is avaiable for .NET Core projects can't be deploy properly because this issue.

Thanks.

PD: Not sure if this was the right place to comment on this or better to pen a new issue.

**Comment by MojoDK** [comment]
Why is this closed? I still have problems with SNI not deployed in ClickOnce.

**Comment by Siam1205** [comment]
> Starting with v2.0.0 of Microsoft.Data.SqlClient, you should not have issues with Clickonce application deployments.
> Please upgrade and let us know if you face any issues! A new issue with repro in that case would be ideal.

I tested it with v2.0.1 now and it works as expected. Finally, I can verify that the issue has been fixed properly and entirely.

@MojoDK It works for my C# ClickOnce application targeting NET 4.7.2. Among others, the solution contains a GUI and a Core assembly. Both include the *Microsoft.Data.SqlClient* v2.0.1 nuget package.

**Comment by MojoDK** [comment]
@Siam1205  ... Well the package says 2.1.1, but the version in VS says 2.0.20168.4:

![2021-02-22_11-36-38](https://user-images.githubusercontent.com/1185948/108696937-7fd54600-7502-11eb-8c41-0a605b29bb49.png)

It does not work for our VB.Net ClickOnce Outlook VSTO addin. No SNI flies are being published.

**Comment by jeremy-waguet** [comment]
Did you purge %USERNAME%\.nuget directory? For some reason an old package version is sometime used instead of the latest one.On 22 Feb 2021 11:39, Mojo <notifications@github.com> wrote:
@Siam1205  ... Well the package says 2.1.1, but the version in VS says 2.0.20168.4:

It does not work for our VB.Net ClickOnce Outlook VSTO addin. No SNI flies are being published.

**Comment by MojoDK** [comment]
@jeremy-waguet  ... that did not help. I deleted all pacakages under %userprofile%.nuget, I removed the Microsoft.Data.SqlClient from my project and added it again. When publised it throws this exception:
  
System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: DLL 'Microsoft.Data.SqlClient.SNI.x64.dll' The specified module could not be found.

**Comment by Siam1205** [comment]
> FYI: I fixed this and following issues by adding
> 
> ```
> <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
> <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
> ```
> 
> to the corresponding `.csproj` file.

Die you try this? I also ran into the exact exception you mentioned. I fiddled with the nuget packages and managed to fix it just to get the exception i mentioned a few comments above.

The quoted lines in combination with the newest nuget packages fixed it for me.

**Comment by MojoDK** [comment]
@Siam1205 ... I tried adding the two lines to the PropertyGroup of the vbproj file, but still same error and I am on latest packages.

**Comment by ErikEJ** [comment]
@MojoDK I suggest you open a new issue, and provide a repro solution, that demonstrates the issue. Notice that a VB.NET based VSTO addin is not a standard executable app.

**Comment by mantasgl** [comment]
I still can get an issue when SNI deploy files are not published to ClickOnce Publishing Folder Location. These files:
- Microsoft.Data.SqlClient.SNI.x64.dll.deploy
- Microsoft.Data.SqlClient.SNI.x86.dll.deploy

Although DLLs are published:
- Microsoft.Data.SqlClient.SNI.x64.dll
- Microsoft.Data.SqlClient.SNI.x86.dll

Steps to reproduce:
1. Build and Publish project with Configuration "Release". 
2. If it is the first build and publish, when SNI deploy files are published.
3. Change Publishing Folder Location.
4. Publish again and SNI deploy files are missing

I tried viewing verbose build log Output and noticed that SNI target "AppendSNIDllsInManifest" is not called, because it depends on Target "BeforeBuild" and "BeforeBuild" is not called because MSBuild decides that not much have changed and no need to run many Targets.

Same issues can be reproduced also by these things:
- switch to other Configuration (in my case I use custom configuration) after previous successful publish

**Comment by julealgon** [comment]
I was having this issue with a normal "publish to folder" process. After adding SNI v.2.1.1 to the executable project, it started being copied to the publish directory correctly.

**Comment by julealgon** [comment]
> I was having this issue with a normal "publish to folder" process. After adding SNI v.2.1.1 to the executable project, it started being copied to the publish directory correctly.
> 
> EDIT: Upon further inspection, turns out this didn't actually solve the issue.... even though the `Microsoft.Data.SqlClient.SNI` DLLs were copied, the corresponding `SNI.dll` files under `x86` and `x64` folders were not...
> 
> Back to square one...

EDIT 2: Ok... found another post here
- https://github.com/dotnet/SqlClient/issues/361

Then proceed to add the `Microsoft.Data.SqlClient v1.1.3` package (the version we were using in the solution) to the project. Didn't work. _Then_, I _removed_ `Microsoft.Data.SqlClient.SNI` package and _did work_: the x64 and x86 folders started being copied, even though the `Microsoft.Data.SqlClient.SNI` dlls were not there.

This is _incredibly_ confusing to me but the important part is that it works now...
