### ISSUE TITLE
SemaphoreFullException in DbConnectionPool.PutNewObject

### ISSUE THREAD

**Issue by saikatguha** [dotnet/SqlClient#708]
Microsoft.Data.SqlClient version: 1.1.3
.NET target: netcoreapp2.2
Environment: Azure Functions App
SQL Server version: Azure SQL Database
Operating System: Windows 

### Describe the bug

I am intermittently seeing a large number of SemaphoreFullExceptions and SqlException since yesterday when connecting to Azure SQL Databases from Azure Functions App. Completely restarting the functions app fixes the problem (for a while) until it reappears after a few hours.

```
Exception message:  Adding the specified count to the semaphore would cause it to exceed its maximum count.
Stack trace:
**System.Threading.SemaphoreFullException**:
   at System.Threading.Semaphore.Release (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at **Microsoft.Data.ProviderBase.DbConnectionPool.PutNewObject** (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.DeactivateObject (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PutObject (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.CloseConnection (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlConnection.CloseInnerConnection (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlConnection.Close (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
```

Sometimes these are accompanied with the following exception:

```
Inner exception **Microsoft.Data.SqlClient.SqlException** handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw:
   at **Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod** (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
```

**Comment by JRahnama** [comment]
Hi @saikatguha couple of things to start with:
1- Can you test your application with the latest version of M.D.S v2.0.0.0 or the preview release  Version=2.1.0-preview1.20235.1
2- Since netcore2.2 EOL was on December 23, 2019 can you test the application with netcore3.1 or netcore2.1 please, to see if the same issue comes up?
3- is it possible to provide us a repro to start with?

**Comment by saikatguha** [comment]
The original bug is intermittent, so it will take some time to repro, or conclude if it is resolved.

I switched dotnet framework to version netcoreapp3.1 but still on M.D.S package version 1.1.3. 
So far I don't see a repro yet, but will wait a few weeks to definitively conclude. 
I am unable to use M.D.S package version 2.0.0 due to some dependency issues.

If I don't post a repro by October 1, 2020 please close this bug as resolved. Thanks!

**Comment by JRahnama** [comment]
@saikatguha Thanks for the response I will tag the issue as Waiting for client responses so we can come back here every week and check the status until October first. Hopefully the issue is resolved.

**Comment by saikatguha** [comment]
Moving to netcoreapp3.1 has not fixed the problem.

```
Adding the specified count to the semaphore would cause it to exceed its maximum count.
System.Threading.SemaphoreFullException:
   at System.Threading.Semaphore.ReleaseCore (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Threading.Semaphore.Release (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PutNewObject (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.DeactivateObject (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PutObject (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.CloseConnection (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlConnection.CloseInnerConnection (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlConnection.Close (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
```


Perhaps related or maybe unrelated, I am also occasionally seeing large bursts of the following exceptions, during which time no queries can be executed, even though there is no issue with credentials.

```
A connection was successfully established with the server, but then an error occurred during the login process. (provider: TCP Provider, error: 0 - The handle is invalid.) The handle is invalid.
Microsoft.Data.SqlClient.SqlException:
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen (Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
Inner exception System.ComponentModel.Win32Exception handled at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod:
```

**Comment by JRahnama** [comment]
@saikatguha can you provide a sample repro of your application please?

**Comment by saikatguha** [comment]
```csharp
using (var connection = new SqlConnection(_connectionString)) {
    var command = GetSqlCommand(connection, query, parameters);
    if (command.Connection.State == ConnectionState.Closed) {
        await command.Connection.OpenAsync();
    }
    if (timeout != null) {
        command.CommandTimeout = timeout.Value;
    }

    using (var reader = await command.ExecuteReaderAsync()) {
        while (await reader.ReadAsync()) {
            ...
        }
     }
    
    return result;
}
```

Connection string is:
```
Server=tcp:****.database.windows.net,1433;Initial Catalog=****;Persist Security Info=False;User ID=****;Password=****;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
```

**Comment by JRahnama** [comment]
@saikatguha is possible to have
GetSqlcommand function, query and parameters as well?

**Comment by saikatguha** [comment]
```csharp
        private SqlCommand GetSqlCommand(SqlConnection connection, string query, IDictionary<string, object> parameters) {
            var command = new SqlCommand(query, connection) {
                CommandTimeout = _defaults.Value.Timeout
            };
            if (parameters != null) {
                foreach (var item in parameters) {
                    if (item.Value == null) {
                        command.Parameters.Add(new SqlParameter($"@{item.Key}", DBNull.Value));
                    } else if (item.Value is SqlParameter p) {
                        command.Parameters.Add(p);
                    } else {
                        command.Parameters.Add(new SqlParameter($"@{item.Key}", item.Value));
                    }
                }
            }
            return command;
        }
```

**Comment by saikatguha** [comment]
I am not logging the query/parameters currently. After instrumenting, will take some time to repro to get a trace. How essential is the query? The exception above throws on the call to `OpenAsync()` before the query is executed.

**Comment by JRahnama** [comment]
> I am not logging the query/parameters currently. After instrumenting, will take some time to repro to get a trace. How essential is the query? The exception above throws on the call to `OpenAsync()` before the query is executed.

That will help to understand the situation better. 

However, what I can see now, although you are disposing the `connection`, the `command` is not disposed. I am not sure if that leaves some resources open (finalizer and subsequently GC is not called on them). Since you are calling the connection from `SqlCommand`, my guess is that prevents the connection from closing and if a connection is not closed it wont be added to the pool and a new connection will be created. There is a maximum number of concurrent entries in `DbConnectionPool ` semaphore. The pool is automatically cleared after a fatal error happens and the loop goes on. One easy possible test for this theory is wrapping your` SqlCommand` in a using statement and see if the error comes up, or simply call connection.OpenAsync directly or check the state from the connection directly.

**Comment by saikatguha** [comment]
I will dispose SqlCommand and report back if the error reoccurs. As before, might take a few weeks to repro. If I don't post by November 1, feel free to close as resolved. Thanks!

**Comment by JRahnama** [comment]
@saikatguha, I am following up to see if the issue has been fixed by suggested solution before closing it.

**Comment by saikatguha** [comment]
I've haven't seen a repro since disposing SqlCommand. Please close as resolved. Thanks!
